import React, { useState, useEffect, useRef } from 'react';
import {
  Card,
  Button,
  message,
  Result,
  Descriptions,
  Space,
  Divider,
  Spin,
  Tag,
  Modal,
} from 'antd';
import {
  RedoOutlined,
  FileTextOutlined,
  BarChartOutlined,
  ClockCircleOutlined,
  PictureOutlined,
} from '@ant-design/icons';
import { useSearchParams, useLocation, useNavigate } from 'react-router-dom';
import QuizGenerator from '../components/Quiz/QuizGenerator';
import QuizTaker from '../components/Quiz/QuizTaker';
import { QuizSettings, QuizQuestion, QuizAnswer, QuizResponse } from '../types';
import { useQuestionStore } from '../store/questionStore';
import { apiClient } from '../api/client';
import KatexRenderer from '../components/Latex/KatexRenderer';

const Quiz: React.FC = () => {
  const [searchParams] = useSearchParams();
  const location = useLocation();
  const navigate = useNavigate();
  const paperId = searchParams.get('paperId');
  const subjectFromUrl = searchParams.get('subject');
  const modeFromUrl = searchParams.get('mode');

  const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
  const [quizStarted, setQuizStarted] = useState(false);
  const [quizFinished, setQuizFinished] = useState(false);
  const [quizResults, setQuizResults] = useState<QuizResponse | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [loading, setLoading] = useState(false);
  const [paperDuration, setPaperDuration] = useState<number>(0);
  const [quizTitle, setQuizTitle] = useState<string>('正在答题');
  const [submitProgress, setSubmitProgress] = useState<string>('');

  // ⭐ 卷子页图
  const [paperPageCount, setPaperPageCount] = useState<number>(0);

  // ⭐ 原图预览状态
  const [imagePreview, setImagePreview] = useState<{ page: number } | null>(null);

  const { generateQuiz } = useQuestionStore();

  const autoGeneratedRef = useRef(false);
  const stateLoadedRef = useRef(false);

  // 1. 从 location.state 加载题目
  useEffect(() => {
    if (stateLoadedRef.current) return;
    const stateQuestions = (location.state as any)?.questions;
    if (stateQuestions && Array.isArray(stateQuestions) && stateQuestions.length > 0) {
      stateLoadedRef.current = true;
      console.log('📥 从 location.state 接收题目:', stateQuestions.length, '道');

      const normalized: QuizQuestion[] = stateQuestions.map((q: any) => ({
        ...q,
        id: q.id || q.question_id,
        score: q.score ?? q.exam?.score ?? 0,
        options: q.options || {},
      }));

      setQuizQuestions(normalized);
      setQuizStarted(true);
      setQuizFinished(false);
      setPaperDuration(0);

      const title = (location.state as any)?.title || '错题专项练习';
      setQuizTitle(title);

      navigate(location.pathname, { replace: true, state: null });

      message.success(`已加载 ${normalized.length} 道错题，开始答题吧`);
    }
  }, [location.state, location.pathname, navigate]);

  // 2. 卷子模式
  useEffect(() => {
    if (paperId) {
      loadPaperQuiz(paperId);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [paperId]);

  // 3. 学科模式
  useEffect(() => {
    if (
      !paperId &&
      subjectFromUrl &&
      modeFromUrl === 'subject' &&
      !autoGeneratedRef.current &&
      !stateLoadedRef.current
    ) {
      autoGeneratedRef.current = true;
      handleGenerateQuiz({
        subjects: [subjectFromUrl],
        count: 10,
        difficulty_distribution: { 基础: 30, 中等: 50, 拔高: 20 },
        types: ['选择题', '填空题', '解答题'],
        include_reviewed: false,
        include_wrong: false,
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [paperId, subjectFromUrl, modeFromUrl]);

  const loadPaperQuiz = async (pid: string) => {
    setLoading(true);
    try {
      const questions = await apiClient.generateQuizFromPaper(pid);
      if (!questions || questions.length === 0) {
        message.warning('该卷子暂无题目');
        return;
      }

      let duration = 0;
      let pageCount = 0;
      try {
        const paperData = await apiClient.getPaper(pid);
        duration = paperData?.duration || 0;
        // ⭐ 读取页图数量
        const pageImages = (paperData as any)?.page_images || [];
        pageCount = Array.isArray(pageImages) ? pageImages.length : 0;
        console.log('📷 卷子页图数量:', pageCount, '页图:', pageImages);
      } catch (e) {
        console.warn('获取卷子详情失败', e);
      }

      setPaperDuration(duration);
      setPaperPageCount(pageCount);
      setQuizQuestions(questions);
      setQuizStarted(true);
      setQuizFinished(false);
      setQuizTitle('正在答题');

      // 调试：看题目有没有 source_page
      const sample = questions.slice(0, 3).map((q: any) => ({
        id: q.id,
        number: q.number,
        source_page: q.source_page,
      }));
      console.log('📋 前 3 题 source_page 字段:', sample);

      message.success(
        `已加载卷子，共 ${questions.length} 道题${duration > 0 ? `，时长 ${duration} 分钟` : ''}`
      );
    } catch (error: any) {
      message.error(error.message || '加载卷子失败');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateQuiz = async (settings: QuizSettings) => {
    try {
      const questions = await generateQuiz(settings);
      if (questions.length === 0) {
        message.warning('没有生成任何题目，请调整筛选条件');
        return;
      }
      setPaperDuration(0);
      setPaperPageCount(0);
      setQuizQuestions(questions);
      setQuizStarted(true);
      setQuizFinished(false);
      setQuizTitle('正在答题');
      if (subjectFromUrl && modeFromUrl === 'subject') {
        message.success(`已自动生成「${subjectFromUrl}」专项练习，共 ${questions.length} 题`);
      } else {
        message.success(`已生成 ${questions.length} 道题目`);
      }
    } catch (error: any) {
      message.error(error.message || '组卷失败');
    }
  };

  const normalizeResults = (raw: any, questions: QuizQuestion[]) => {
    const rawResults = raw?.results;
    if (!rawResults) return [];

    let arr: any[] = [];
    if (Array.isArray(rawResults)) {
      arr = rawResults;
    } else if (typeof rawResults === 'object') {
      arr = Object.entries(rawResults).map(([qid, v]: [string, any]) => ({
        question_id: qid,
        ...(typeof v === 'object' && v !== null ? v : {}),
      }));
    }

    return arr.map((r: any) => {
      const q = questions.find((x) => x.id === r.question_id);
      const nested = r.ai_result || {};
      const fullScore = r.full_score ?? (q as any)?.score ?? 5;
      const score = r.score ?? nested.score ?? 0;

      const isCorrectByScore = fullScore > 0 ? (score >= fullScore * 0.99) : false;
      const isCorrectFromBackend = r.is_correct ?? nested.is_correct ?? false;
      const finalIsCorrect = score > 0 ? (isCorrectFromBackend || isCorrectByScore) : false;

      return {
        question_id: r.question_id,
        user_answer: r.user_answer ?? '',
        correct_answer: r.correct_answer ?? q?.answer ?? '',
        is_correct: finalIsCorrect,
        score: score,
        full_score: fullScore,
        ai_score_pct: r.ai_score_pct ?? 0,
        ai_feedback: r.ai_feedback ?? r.feedback ?? nested.ai_feedback ?? '',
        detailed_analysis:
          r.detailed_analysis ??
          r.analysis ??
          r.explanation ??
          nested.detailed_analysis ??
          '',
        explanation: r.explanation ?? q?.explanation ?? '',
      };
    });
  };

  const handleSubmitQuiz = async (answers: QuizAnswer[]) => {
    setIsSubmitting(true);
    setSubmitProgress('⏳ 正在准备批改数据...');

    try {
      console.log('📝 提交的答案:', answers);

      const { task_id } = await apiClient.submitQuizAsync(answers);
      console.log('🎯 批改任务ID:', task_id);

      const pollInterval = 800;
      const maxWait = 10 * 60 * 1000;
      const startTime = Date.now();

      while (Date.now() - startTime < maxWait) {
        await new Promise((r) => setTimeout(r, pollInterval));

        let status: any;
        try {
          status = await apiClient.getQuizSubmitStatus(task_id);
        } catch (err) {
          continue;
        }

        const stage = status.stage || '';
        const cur = status.current || 0;
        const total = status.total || answers.length;

        if (stage === 'preparing') {
          setSubmitProgress('⏳ 正在准备批改数据...');
        } else if (stage === 'grading') {
          setSubmitProgress(`🤖 AI 正在批改 ${cur}/${total} 题...`);
        } else if (stage === 'saving') {
          setSubmitProgress('💾 正在保存结果...');
        }

        if (status.status === 'done') {
          const raw = status.result;
          const normalized = normalizeResults(raw, quizQuestions);

          const totalScore =
            raw?.total_score ??
            normalized.reduce((s, r) => s + (Number(r.score) || 0), 0);
          const maxScore =
            raw?.max_score ??
            normalized.reduce((s, r) => s + (Number(r.full_score) || 0), 0);

          setQuizResults({
            results: normalized,
            total_score: Math.round(totalScore * 100) / 100,
            max_score: Math.round(maxScore * 100) / 100,
          });
          setQuizFinished(true);
          message.success('试卷批改完成！');
          return;
        }

        if (status.status === 'error') {
          throw new Error(status.error || '批改失败');
        }
      }

      throw new Error('批改超时，请稍后重试');
    } catch (error: any) {
      console.error('提交失败:', error);
      message.error(error.message || '提交失败');
    } finally {
      setIsSubmitting(false);
      setSubmitProgress('');
    }
  };

  const restartQuiz = () => {
    setQuizStarted(false);
    setQuizFinished(false);
    setQuizQuestions([]);
    setQuizResults(null);
    setPaperDuration(0);
    setPaperPageCount(0);
    setQuizTitle('正在答题');
    setSubmitProgress('');
    setImagePreview(null);
    autoGeneratedRef.current = false;
    stateLoadedRef.current = false;
    if (paperId || subjectFromUrl) {
      window.history.replaceState({}, '', '/quiz');
    }
  };

  const renderWithLatex = (text: string) => {
    if (!text) return <span style={{ color: '#999' }}>无内容</span>;
    const parts = text.split(/(\$[^$]+\$)/);
    return parts.map((part, index) => {
      if (part.startsWith('$') && part.endsWith('$')) {
        const latex = part.slice(1, -1);
        return <KatexRenderer key={index} content={latex} />;
      }
      return <span key={index}>{part}</span>;
    });
  };

  // ⭐ 原图预览 Modal（带页码切换）
  const renderImagePreview = () => (
    <Modal
      open={!!imagePreview}
      onCancel={() => setImagePreview(null)}
      footer={null}
      width={1000}
      title={imagePreview ? `📷 原图预览 - 第 ${imagePreview.page} 页` : ''}
      styles={{ body: { maxHeight: '75vh', overflow: 'auto', textAlign: 'center' } }}
      destroyOnClose
    >
      {imagePreview && paperId && (
        <div>
          {/* 页码切换 */}
          {paperPageCount > 1 && (
            <Space style={{ marginBottom: 12, flexWrap: 'wrap' }}>
              {Array.from({ length: paperPageCount }, (_, i) => i + 1).map((p) => (
                <Button
                  key={p}
                  size="small"
                  type={imagePreview.page === p ? 'primary' : 'default'}
                  onClick={() => setImagePreview({ page: p })}
                >
                  第 {p} 页
                </Button>
              ))}
            </Space>
          )}

          <div>
            <img
              src={`/api/papers/${paperId}/page-image/${imagePreview.page}`}
              alt={`第 ${imagePreview.page} 页`}
              style={{ maxWidth: '100%', borderRadius: 6, border: '1px solid #eee' }}
              onError={(e) => {
                (e.target as HTMLImageElement).alt = '图片加载失败';
              }}
            />
          </div>
        </div>
      )}
    </Modal>
  );

  const renderQuestionDetail = (result: any, index: number) => {
    const score = result.score ?? 0;
    const fullScore = result.full_score ?? 3;
    const isCorrect = fullScore > 0 ? score >= fullScore * 0.99 : false;

    const userAnswer = result.user_answer || '未作答';
    const correctAnswer = result.correct_answer || '';
    const aiFeedback = result.ai_feedback || '';
    const detailedAnalysis = result.detailed_analysis || '';
    const question = quizQuestions.find((q) => q.id === result.question_id);
    const pct = fullScore > 0 ? Math.round((score / fullScore) * 100) : 0;
    const sourcePage = (question as any)?.source_page as number | undefined;

    return (
      <Descriptions.Item
        key={index}
        label={`第 ${index + 1} 题 ${isCorrect ? '✅' : '❌'}`}
        labelStyle={{ fontWeight: 'bold', color: isCorrect ? 'green' : 'red' }}
      >
        <Space direction="vertical" size="middle" style={{ width: '100%' }}>
          <div>
            <strong>题目:</strong>
            <div className="p-2 bg-gray-50 rounded mt-1">
              {renderWithLatex(question?.content || '')}
            </div>
          </div>

          {question?.options && Object.keys(question.options).length > 0 && (
            <div>
              <strong>选项:</strong>
              <div className="p-2 bg-gray-50 rounded mt-1">
                {Object.entries(question.options).map(([k, v]) => (
                  <div key={k}>
                    <strong>{k}.</strong> {renderWithLatex(v as string)}
                  </div>
                ))}
              </div>
            </div>
          )}

          <div>
            <strong>您的答案:</strong>
            <div
              className="p-2 bg-gray-50 rounded mt-1"
              style={{ color: isCorrect ? 'green' : 'red' }}
            >
              {renderWithLatex(userAnswer)}
            </div>
          </div>

          <div>
            <strong>正确答案:</strong>
            <div className="p-2 bg-gray-50 rounded mt-1" style={{ color: 'green' }}>
              {renderWithLatex(correctAnswer || question?.answer || '未提供')}
            </div>
          </div>

          {/* ⭐ 每题下方：如果有 source_page，显示跳页按钮 */}
          {paperId && sourcePage && (
            <div>
              <Button
                size="small"
                icon={<PictureOutlined />}
                onClick={() => setImagePreview({ page: sourcePage })}
              >
                查看原图（第 {sourcePage} 页）
              </Button>
            </div>
          )}

          <Divider />

          <div style={{ background: '#f0f7ff', padding: 12, borderRadius: 6 }}>
            <h4 style={{ margin: 0, marginBottom: 8 }}>🤖 AI 批改报告</h4>
            <div>
              <strong>得分:</strong> {score} / {fullScore} 分
              <span style={{ marginLeft: 8, color: '#888', fontSize: 13 }}>
                （AI 评分 {result.ai_score_pct ?? pct}%）
              </span>
            </div>

            {aiFeedback && (
              <div className="mt-1">
                <strong>反馈:</strong>
                <div className="p-2 bg-white rounded mt-1 text-blue-700">
                  {renderWithLatex(aiFeedback)}
                </div>
              </div>
            )}

            {detailedAnalysis && (
              <div className="mt-2">
                <strong>📝 详细分析:</strong>
                <div
                  className="p-2 bg-white rounded mt-1 text-gray-800 border border-gray-200"
                  style={{ whiteSpace: 'pre-wrap' }}
                >
                  {renderWithLatex(detailedAnalysis)}
                </div>
              </div>
            )}

            {!aiFeedback && !detailedAnalysis && (
              <div className="text-gray-400 text-sm">暂无 AI 详细分析</div>
            )}
          </div>
        </Space>
      </Descriptions.Item>
    );
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <Spin size="large" />
        <span className="ml-4">加载卷子中...</span>
      </div>
    );
  }

  if (quizFinished && quizResults) {
    const correctCount = quizResults.results.filter((result: any) => result.is_correct).length;
    const totalCount = quizResults.results.length;
    const scorePercentage =
      quizResults.max_score > 0
        ? ((quizResults.total_score / quizResults.max_score) * 100).toFixed(1)
        : '0';

    return (
      <div className="max-w-4xl mx-auto">
        <Result
          status={correctCount === totalCount ? 'success' : 'info'}
          title="测试完成！"
          subTitle={
            <Space direction="vertical" size="large">
              <div>
                您的得分: <strong>{quizResults.total_score}</strong> / {quizResults.max_score} 分
              </div>
              <div>
                正确率: {correctCount}/{totalCount} 题 ({scorePercentage}%)
              </div>
            </Space>
          }
          extra={[
            <Button key="restart" type="primary" onClick={restartQuiz} icon={<RedoOutlined />}>
              返回组卷
            </Button>,
            <Button key="details" onClick={() => setQuizFinished(false)} icon={<BarChartOutlined />}>
              查看答题详情
            </Button>,
          ]}
        />

        {quizResults.results && (
          <Card title="答题详情" className="mt-6">
            <Descriptions column={1} bordered>
              {quizResults.results.map((result, index) => renderQuestionDetail(result, index))}
            </Descriptions>
          </Card>
        )}

        {renderImagePreview()}
      </div>
    );
  }

  if (quizStarted) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-6 flex-wrap gap-2">
          <h2 className="text-2xl font-bold">
            {quizTitle}
            {subjectFromUrl && modeFromUrl === 'subject' && (
              <Tag color="blue" style={{ marginLeft: 12 }}>
                {subjectFromUrl} 专项
              </Tag>
            )}
          </h2>
          <Space wrap>
            {paperDuration > 0 && (
              <Tag color="blue" icon={<ClockCircleOutlined />}>
                限时 {paperDuration} 分钟
              </Tag>
            )}
            {/* ⭐ 答题页全局"查看原图"按钮 */}
            {paperId && paperPageCount > 0 && (
              <Button
                icon={<PictureOutlined />}
                onClick={() => setImagePreview({ page: 1 })}
              >
                查看原图（{paperPageCount} 页）
              </Button>
            )}
            <Button onClick={restartQuiz} icon={<RedoOutlined />} disabled={isSubmitting}>
              重新组卷
            </Button>
          </Space>
        </div>

        <QuizTaker
          questions={quizQuestions}
          onSubmit={handleSubmitQuiz}
          isSubmitting={isSubmitting}
          submittingText={submitProgress}
          duration={paperDuration}
          showTimer={paperDuration > 0}
        />

        {renderImagePreview()}
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto">
      <div className="text-center mb-8">
        <h2 className="text-3xl font-bold mb-2">智能组卷</h2>
        <p className="text-gray-600">根据您的需求智能生成个性化试卷</p>
      </div>

      <QuizGenerator onGenerate={handleGenerateQuiz} />

      {quizQuestions.length > 0 && !quizStarted && (
        <Card className="mt-6">
          <div className="text-center">
            <FileTextOutlined className="text-4xl text-green-500 mb-4" />
            <h3 className="text-xl font-semibold mb-2">试卷准备就绪</h3>
            <p>已生成 {quizQuestions.length} 道题目，随时可以开始答题</p>
            <Button
              type="primary"
              size="large"
              className="mt-4"
              onClick={() => setQuizStarted(true)}
            >
              开始答题
            </Button>
          </div>
        </Card>
      )}
    </div>
  );
};

export default Quiz;